apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-mysql
        image: mysql-local:latest
        imagePullPolicy: Never
        command: ['sh', '-c', 'until mysqladmin ping -h mysql -u Admin -p@Admin002 --silent; do echo waiting for mysql; sleep 2; done']
      containers:
      - name: backend
        image: backend:local
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_NAME
          value: camu_ecoa_db
        - name: DB_USER
          value: Admin
        - name: DB_PASSWORD
          value: "@Admin002"
        - name: DATABASE_URL
          value: "mysql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):3306/$(DB_NAME)?connection_limit=5&connect_timeout=30&pool_timeout=30"
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: my-app
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
