apiVersion: v1
kind: Pod
metadata:
  name: network-test
  namespace: my-app
spec:
  containers:
  - name: network-test
    image: curlimages/curl
    command: ['sh', '-c', 'while true; do sleep 30; done'] 