apiVersion: v1
kind: Pod
metadata:
  name: network-test
  namespace: my-app
spec:
  containers:
  - name: network-test
    image: mysql-local:latest
    imagePullPolicy: Never
    command: ['sh', '-c', 'apt-get update && apt-get install -y curl && while true; do sleep 30; done'] 