apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helmreleases.helm.toolkit.fluxcd.io
spec:
  group: helm.toolkit.fluxcd.io
  names:
    kind: HelmRelease
    listKind: HelmReleaseList
    plural: helmreleases
    singular: helmrelease
  scope: Namespaced
  versions:
    - name: v2beta1
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["chart"]
              properties:
                interval:
                  type: string
                  pattern: "^([0-9]+(\\.[0-9]+)?(ms|s|m|h))+$"
                chart:
                  type: object
                  required: ["spec"]
                  properties:
                    spec:
                      type: object
                      required: ["chart"]
                      properties:
                        chart:
                          type: string
                        version:
                          type: string
                        sourceRef:
                          type: object
                          required: ["kind", "name"]
                          properties:
                            kind:
                              type: string
                              enum: ["HelmRepository", "GitRepository", "Bucket"]
                            name:
                              type: string 