apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kustomizations.kustomize.toolkit.fluxcd.io
spec:
  group: kustomize.toolkit.fluxcd.io
  names:
    kind: Kustomization
    listKind: KustomizationList
    plural: kustomizations
    singular: kustomization
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["path", "sourceRef"]
              properties:
                path:
                  type: string
                interval:
                  type: string
                  pattern: "^([0-9]+(\\.[0-9]+)?(ms|s|m|h))+$"
                prune:
                  type: boolean
                sourceRef:
                  type: object
                  required: ["kind", "name"]
                  properties:
                    kind:
                      type: string
                      enum: ["GitRepository"]
                    name:
                      type: string 