apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: alerts.notification.toolkit.fluxcd.io
spec:
  group: notification.toolkit.fluxcd.io
  names:
    kind: Alert
    listKind: AlertList
    plural: alerts
    singular: alert
  scope: Namespaced
  versions:
    - name: v1beta2
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["providerRef", "eventSeverity", "eventSources"]
              properties:
                providerRef:
                  type: object
                  required: ["name"]
                  properties:
                    name:
                      type: string
                eventSeverity:
                  type: string
                  enum: ["info", "error"]
                eventSources:
                  type: array
                  items:
                    type: object
                    required: ["kind", "name"]
                    properties:
                      kind:
                        type: string
                      name:
                        type: string 