apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gitrepositories.source.toolkit.fluxcd.io
spec:
  group: source.toolkit.fluxcd.io
  names:
    kind: GitRepository
    listKind: GitRepositoryList
    plural: gitrepositories
    singular: gitrepository
  scope: Namespaced
  versions:
    - name: v1beta2
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .spec.url
          name: URL
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["url"]
              properties:
                url:
                  type: string
                interval:
                  type: string
                  pattern: "^([0-9]+(\\.[0-9]+)?(ms|s|m|h))+$"
                ref:
                  type: object
                  properties:
                    branch:
                      type: string
                    commit:
                      type: string
                    tag:
                      type: string
                    semver:
                      type: string 